stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:latest
  script:
    - echo "Building mdhashim.com"
    - npm install
    - npm run build-app
    - echo "Built App"
    - ls -lah dist/
  artifacts:
    when: on_success
    access: all
    paths:
      - dist/



deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - main
  script:
    - #aws configure list
    - echo "Provisioning website to s3."
    - #aws s3 cp dist s3://build-app --recursive
    - echo "Successfully provisioned the app to S3."
    - echo "App Version"
    - cat src/AppConfig.json
